// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class 2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 2() {
    // Test name: 2
    // Step # | name | target | value
    // 1 | open | https://www.fandom.com/ | 
    driver.get("https://www.fandom.com/");
    // 2 | setWindowSize | 1760x477 | 
    driver.manage().window().setSize(new Dimension(1760, 477));
    // 3 | click | css=.global-explore-navigation__home-link .wds-icon | 
    driver.findElement(By.cssSelector(".global-explore-navigation__home-link .wds-icon")).click();
    // 4 | mouseOver | css=.global-explore-navigation__home-link .wds-icon | 
    {
      WebElement element = driver.findElement(By.cssSelector(".global-explore-navigation__home-link .wds-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | mouseOut | css=.global-explore-navigation__home-link .wds-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | runScript | window.scrollTo(0,1.8333333730697632) | 
    js.executeScript("window.scrollTo(0,1.8333333730697632)");
    // 7 | click | css=.fandom-theme-1:nth-child(4) .feed-card__title | 
    driver.findElement(By.cssSelector(".fandom-theme-1:nth-child(4) .feed-card__title")).click();
    // 8 | runScript | window.scrollTo(0,4.583333492279053) | 
    js.executeScript("window.scrollTo(0,4.583333492279053)");
    // 9 | mouseOver | linkText=Darryn Bonthuys | 
    {
      WebElement element = driver.findElement(By.linkText("Darryn Bonthuys"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
